version: "3"

services:
  mysql:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=ahgathumeiguaPaiWaichefahj2uph4a"
    ports: 
      - "3306:3306"
    volumes:
      - "./mysqlData:/var/lib/mysql"
      - "./Dump20180111.sql:/docker-entrypoint-initdb.d/Dump20180111.sql"

  backend:
    build: buildContextBackend
    environment:
      - "DB_HOST=mysql"
      - "DB_NAME=studyvote"
      - "DB_PORT=3306"
      - "DB_ROOT_PASSWORD=ahgathumeiguaPaiWaichefahj2uph4a"
      - "SERVER_PORT=1337"
    ports:
      - "1337:1337"
    depends_on:
      - mysql
  frontend:
    build: buildContextClient
    environment:
      - "REACT_APP_SERVER_HOST=localhost"
      - "REACT_APP_SERVER_PORT=1337"
    ports: 
      - "3000:3000"
    depends_on:
      - backend